# Generated by Django 4.2.21 on 2025-07-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_alter_reservation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="inquiry",
            field=models.TextField(blank=True, null=True),
        ),
    ]
