# Generated by Django 4.2.21 on 2025-07-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_reservation_follow_up_note_reservation_is_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="confirmation_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
