# Generated by Django 4.2.21 on 2025-07-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_reservation_confirmation_email_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="ご予約の方へ一品プレゼント！", max_length=100)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="special_offers/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
